#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if type direnv > /dev/null; then
  eval "$(direnv hook zsh)"
fi

if type nodenv > /dev/null; then
  eval "$(nodenv init -)"
fi

BASE16_SHELL=$HOME/src/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

export KEYTIMEOUT=1

bindkey "^R" history-incremental-search-backward

if [[ `uname` == "CYGWIN_NT-6.1" ]]; then
  export PATH=$PATH:$HOME/bin
  export http_proxy=http://wpad:8080
  export https_proxy=http://wpad:8080
  git-info off
fi

# not currently using ruby
#eval "$(rbenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias vi=nvim
alias dm=docker-machine
alias dc=docker-compose
