#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

if type direnv > /dev/null; then
  eval "$(direnv hook zsh)"
fi

source ~/src/base16-shell/base16-default.dark.sh

export KEYTIMEOUT=1
